spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-develop.yaml
    default-schema: public

